; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc-1-YD-clone]
platform = espressif32
board = esp32-s3-devkitc-1-YD-clone
framework = arduino
lib_deps = fastled/FastLED@^3.7.0

debug_build_flags = -O0 -ggdb3 -g3 ;agressive compiler optimisation cab cause the debugger to dtop a few lines after a breakpoint

;upload_protocol = esptool
;upload_port = COM4
debug_tool = esp-builtin
debug_init_break = tbreak setup
;debug_init_break = break main.cpp:23