; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F407VET6]
platform = ststm32
board = genericSTM32F407VET6
framework = arduino

; Remove the default optimization (usually -Os for size)
build_unflags = -Os

; Force Optimization Level 0 (None) and add maximum debug info
build_flags = 
    -O0 
    -g3
    -fno-eliminate-unused-debug-types
    -Wno-cpp  ; This suppresses the #warning "This wrapper was verified..." message

; Set protocol to 'jlink' which defaults to SWD in the ststm32 platform
upload_protocol = jlink

; Debugging Configuration
debug_tool = jlink
debug_init_break = tbreak setup
debug_extra_cmds =
    monitor if swd
    monitor speed 1000

; Set speed to 1000kHz as requested previously
debug_speed = 1000
