; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:ATtiny1616]
platform = atmelmegaavr
board = ATtiny1616
framework = arduino
board_build.f_cpu = 16000000L
board_hardware.oscillator = internal

upload_protocol = custom
upload_command = upload.bat

build_flags = 
    -D SEGGER_RTT_SECTION="\"SEGGER_RTT\""
monitor_speed = 115200
lib_deps = koendv/RTT Stream@^1.4.1