; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_itsybitsy_m4]
platform = atmelsam
board = adafruit_itsybitsy_m4
debug_tool = jlink
framework = arduino
upload_protocol = jlink
debug_init_break = tbreak setup
lib_deps = koendv/RTT Stream@^1.4.1
monitor_speed = 115200
monitor_filters = time
debug_speed = 1000
build_flags = 
	-O0
	-g3
	-DDEBUG
	-DCORE_DEBUG_LEVEL=5
build_unflags = 
	-Os
	-flto
debug_extra_cmds = 
	;set remote hardware-watchpoint-limit 2
	;set remote hardware-breakpoint-limit 6
	;mon reset
	;mon halt
