; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_itsybitsy_m4]
platform = atmelsam
board = adafruit_itsybitsy_m4
framework = arduino

; Force J-Link for both Upload and Debug
upload_protocol = jlink
debug_tool = jlink

; Ensure we use the safe speed you verified earlier
debug_speed = 1000
upload_speed = 1000

; Fix the 'Cold Start' delay issue we identified
debug_init_break = tbreak setup
debug_extra_cmds =
    monitor reset
    monitor halt