; PlatformIO Project Configuration File
;
; The board is defined as the bare metal chip, not the XIAO, as it works with a fully erased SAMD21
; The binary is loaded at the start of flash memory 0x0000 not the 0x2000 a new XIAO with a bootloader requires

[env:seeed_xiao]
platform = atmelsam
board = samd21g18a
framework = arduino
upload_protocol = jlink
debug_tool = jlink
debug_speed = 2000
board_upload.offset_address = 0x0000
debug_init_break = tbreak setup
build_flags = 
	-DARDUINO_SAMD_XIAO
upload_flags = 
	-speed
	2000
lib_deps = koendv/RTT Stream@^1.4.1
