; ============================================================
; PLATFORMIO.INI - WITH INITIAL BREAKPOINT
; ============================================================

[env]
platform = atmelsam
board = samd21_m0_mini
framework = arduino
monitor_speed = 115200
build_type = debug
debug_tool = jlink
debug_load_mode = manual

; Halts execution at the start of setup()
debug_init_break = tbreak setup

; Add library here so it works for BOTH USB and J-Link envs
lib_deps = koendv/RTT Stream@^1.4.1

[env:samd21_m0_mini_usb]
upload_protocol = sam-ba

[env:samd21_m0_mini_jlink]
upload_protocol = jlink
; RTT-specific monitor settings
monitor_port = socket://localhost:19021
monitor_filters = send_on_enter, colorize