; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:bluepill_f103c8]
platform = ststm32
board = bluepill_f103c8
framework = arduino

; Protocol triggers the JTAG logic in main.py
upload_protocol = jlink-jtag

; Set the upload speed specifically
debug_speed = 1000

; Keeping these for JTAG chain clarity
upload_flags =
    -jtagconf
    -1,-1
    -autoconnect
    1
    -speed
    1000

; Debugging Configuration
debug_tool = jlink
debug_init_break = tbreak setup
debug_extra_cmds =
    monitor if jtag
    monitor speed 1000