; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:adafruit_itsybitsy_m4]
platform = atmelsam
board = adafruit_itsybitsy_m4
framework = arduino

; ---- UPLOAD USING DAP-LINK (SAMD51-compatible) ----
upload_protocol = custom
upload_command = C:\Users\Steven\.platformio\packages\tool-openocd\bin\openocd.exe -s C:\Users\Steven\.platformio\packages\tool-openocd\scripts -f interface/cmsis-dap.cfg -c "adapter speed 500" -f target/atsame5x.cfg -c "init; halt; at91samd unlock 0; at91samd erase 0; program {$SOURCE} verify reset exit"

; ---- DEBUG USING DAP-LINK ----
debug_tool = custom
debug_server =
    C:\Users\Steven\.platformio\packages\tool-openocd\bin\openocd.exe
    -s C:\Users\Steven\.platformio\packages\tool-openocd\scripts
    -f interface/cmsis-dap.cfg
    -c "adapter speed 500"
    -f target/atsame5x.cfg
