[env:demo_f030f4]
platform = ststm32
board = demo_f030f4
framework = arduino

; --- Manual Upload ---
upload_protocol = custom
; Using double quotes for the path to avoid shell parsing warnings
upload_command = "C:/Program Files/SEGGER/JLink/JLink.exe" -device STM32F030F4 -speed 4000 -if SWD -autoconnect 1 -CommanderScript upload.jlink

; --- Debugging Configuration ---
debug_tool = jlink
debug_speed = 4000
debug_init_break = tbreak setup
debug_extra_cmds = monitor reset 0

; --- Hardware Adjustments ---
board_upload.maximum_size = 16384
board_upload.maximum_ram_size = 4096
monitor_speed = 115200